### ISSUE TITLE
New-JiraIssue - Service Desk Get-Member issue

### ISSUE THREAD

**Issue by JoeJe1993** [AtlassianPS/JiraPS#118] opened 2017-05-30 13:39 UTC
When using New-JiraIssue on a Service Desk, an error about an incomplete Get-Member cmdlet comes up in ConvertTo-JiraCreateMetaField.ps1.

This doesn't happen on other types of Jira boards

![image](https://cloud.githubusercontent.com/assets/29064065/26585886/6bb770e4-4545-11e7-870a-9790b037bd2c.png)

![image](https://cloud.githubusercontent.com/assets/29064065/26585970/b116d33c-4545-11e7-91b4-df3f56141441.png)

**Comment by JoeJe1993** [comment] 2017-05-30 14:46
Debug info: 

![image](https://cloud.githubusercontent.com/assets/29064065/26589145/29d0e430-454f-11e7-959b-71e203c8aed6.png)

**Comment by lipkau** [comment] 2017-05-30 14:47
Hi.
Can you please run the command with `-debug`?
I expect for you to get this debug message:

> "[New-JiraIssue] Encountered an error reading configuration data."

If you do, it would be great if you can enter debug mode (suspend) and print `$err | FL * -force`
And show us the result.

**It is important to run that command in the debug mode**, the variable `$err` will be deleted once the function exits

**Comment by JoeJe1993** [comment] 2017-05-30 14:48
Just attached a screenshot with all the debug info for you.

**Comment by lipkau** [comment] 2017-05-30 14:50
It appears that the input object of `issueCreateMeta` is different that the ones  we know. Probably a _service desk_ thing.

@all : can anyone​confirm this?

I will try to reproduce after I get back from my vacation

**Comment by lipkau** [comment] 2017-05-30 19:18
Does `Get-JiraIssueCreateMetadata` return an error too? If not, please attach the output of `Export-Clixml`

**Comment by JoeJe1993** [comment] 2017-05-31 08:39
It returns an error.

![image](https://cloud.githubusercontent.com/assets/29064065/26623225/f79cd690-45e4-11e7-8050-1d670bc3a5dd.png)

**Comment by JoeJe1993** [comment] 2017-06-01 12:52
Hi @lipkau, is what I've provided okay?

**Comment by lipkau** [comment] 2017-06-02 14:18
No. I need the PSObject that is passed on to `ConvertTo-JiraCreateMetaField`

**Comment by lipkau** [comment] 2017-06-02 14:19
I will be able to send you a snippet to get me the info I need tomorrow

**Comment by lipkau** [comment] 2017-06-04 17:50
@JoeJe1993 :
**after** loading the module, please load this into your powershell session:
```posh
function Get-JiraIssueCreateMetadata
{
    <#
    .Synopsis
       Returns metadata required to create an issue in JIRA
    .DESCRIPTION
       This function returns metadata required to create an issue in JIRA - the fields that can be defined in the process of creating an issue.  This can be used to identify custom fields in order to pass them to New-JiraIssue.

       This function is particularly useful when your JIRA instance includes custom fields that are marked as mandatory.  The required fields can be identified from this See the examples for more details on this approach.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'TEST' -IssueType 'Bug'
       This example returns the fields available when creating an issue of type Bug under project TEST.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'JIRA' -IssueType 'Bug' | ? {$_.Required -eq $true}
       This example returns fields available when creating an issue of type Bug under the project Jira.  It then uses Where-Object (aliased by the question mark) to filter only the fields that are required.
    .INPUTS
       This function does not accept pipeline input.
    .OUTPUTS
       This function outputs the PSJira.Field objects that represent JIRA's create metadata.
    .NOTES
       This function requires either the -Credential parameter to be passed or a persistent JIRA session. See New-JiraSession for more details.  If neither are supplied, this function will run with anonymous access to JIRA.
    #>
    [CmdletBinding()]
    param(
        # Project ID or key
        [Parameter(Mandatory = $true,
                   Position = 0)]
        [String] $Project,

        # Issue type ID or name
        [Parameter(Mandatory = $true,
                   Position = 1)]
        [String] $IssueType,

        [String] $ConfigFile,

        # Credentials to use to connect to Jira
        [Parameter(Mandatory = $false)]
        [System.Management.Automation.PSCredential] $Credential
    )

    begin
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Reading server from config file"
        try
        {
            $server = Get-JiraConfigServer -ConfigFile $ConfigFile -ErrorAction Stop
        } catch {
            $err = $_
            Write-Debug "[Get-JiraIssueCreateMetadata] Encountered an error reading the Jira server."
            throw $err
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Building URI for REST call based on parameters"
        $uri = "$server/rest/api/latest/issue/createmeta?"

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining project ID for project [$Project]"
        $projectObj = Get-JiraProject -Project $Project -Credential $Credential
        if ($projectObj)
        {
            $projectId = $projectObj.Id
            $uri = "${uri}projectIds=$projectId&"
        } else {
            throw "No project was found for the given Project [$Project]. Use Get-JiraProject for more information on this issue."
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining issue type ID for issue type [$IssueType]"
        $issueTypeObj = Get-JiraIssueType -IssueType $IssueType -Credential $Credential
        if ($issueTypeObj)
        {
            $issueTypeId = $issueTypeObj.Id
            $uri = "${uri}issuetypeIds=$issueTypeId&"
        } else {
            throw "No issue types were found for the given IssueType [$IssueType]. Use Get-JiraIssueType for more information on this issue."
        }

        $uri = "${uri}expand=projects.issuetypes.fields"
    }

    process
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Preparing for blastoff!"
        $jiraResult = Invoke-JiraMethod -Method Get -URI $uri -Credential $Credential

        if ($jiraResult)
        {
            if (@($jiraResult.projects).Count -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No project results were found. Throwing exception."
                throw "No projects were found for the given project [$Project]. Use Get-JiraProject for more details."
            } elseif (@($jiraResult.projects).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple project results were found. Throwing exception."
                throw "Multiple projects were found for the given project [$Project]. Refine the parameters to return only one project."
            }

            $projectId = $jiraResult.projects.id
            $projectKey = $jiraResult.projects.key

            Write-Debug "[Get-JiraIssueCreateMetadata] Identified project key: [$Project]"

            if (@($jiraResult.projects.issuetypes) -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No issue type results were found. Throwing exception."
                throw "No issue types were found for the given issue type [$IssueType]. Use Get-JiraIssueType for more details."
            } elseif (@($jiraResult.projects.issuetypes).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple issue type results were found. Throwing exception."
                throw "Multiple issue types were found for the given issue type [$IssueType]. Refine the parameters to return only one issue type."
            }

            Write-Debug "[Get-JiraIssueCreateMetadata] Converting results to custom object"
            $global:DEBUG_metadata = $jiraResult
            $obj = ConvertTo-JiraCreateMetaField -InputObject $jiraResult

            Write-Debug "Outputting results"
            Write-Output $obj

#            Write-Output $jiraResult
        } else {
            Write-Debug "[Get-JiraIssueCreateMetadata] No results were returned from JIRA."
        }
    }
}
```

after this, please run this command:
```posh
Get-JiraIssueCreateMetadata -Project DOC -IssueType Task
```
and then give me the output of this command:
```posh
$DEBUG_metadata | convertto-json -Depth 99
```

**Comment by JoeJe1993** [comment] 2017-06-05 08:23
With your new Get-HiraIssueCreateMetadata

![image](https://cloud.githubusercontent.com/assets/29064065/26776332/a1981fb2-49d0-11e7-89dc-6c0343bd23a2.png)

**Comment by JoeJe1993** [comment] 2017-06-05 08:41
Just a quick note, I'm sure you're already aware of this, but this is the environment we're trying to open tickets on.

![image](https://cloud.githubusercontent.com/assets/29064065/26776911/29f05e7c-49d3-11e7-9970-ba3c81d1cfce.png)

**Comment by lipkau** [comment] 2017-06-05 08:44
@JoeJe1993, this function I provided doesn't fix anything.
It only allow you the give me this information is need with these two commands:
> after this, please run this command:
> ```posh
> Get-JiraIssueCreateMetadata -Project DOC -IssueType Task
> ```
> and then give me the output of this command:
> ```posh
> $DEBUG_metadata | convertto-json -Depth 99
> ```

**Comment by JoeJe1993** [comment] 2017-06-05 09:35
Hi @lipkau, apologies, here's the output you wanted.

![image](https://cloud.githubusercontent.com/assets/29064065/26778801/b0e42c7c-49da-11e7-8007-d0c63a2aa695.png)

**Comment by lipkau** [comment] 2017-06-05 09:37
that doesn't look right.
can you paste the command you ran?

**Comment by JoeJe1993** [comment] 2017-06-05 09:40
`Import-Module PSJira

Set-JiraConfigServer -Server 'https://[DOMAIN]:443/jira'

function Get-JiraIssueCreateMetadata
{
    <#
    .Synopsis
       Returns metadata required to create an issue in JIRA
    .DESCRIPTION
       This function returns metadata required to create an issue in JIRA - the fields that can be defined in the process of creating an issue.  This can be used to identify custom fields in order to pass them to New-JiraIssue.

       This function is particularly useful when your JIRA instance includes custom fields that are marked as mandatory.  The required fields can be identified from this See the examples for more details on this approach.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'TEST' -IssueType 'Bug'
       This example returns the fields available when creating an issue of type Bug under project TEST.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'JIRA' -IssueType 'Bug' | ? {$_.Required -eq $true}
       This example returns fields available when creating an issue of type Bug under the project Jira.  It then uses Where-Object (aliased by the question mark) to filter only the fields that are required.
    .INPUTS
       This function does not accept pipeline input.
    .OUTPUTS
       This function outputs the PSJira.Field objects that represent JIRA's create metadata.
    .NOTES
       This function requires either the -Credential parameter to be passed or a persistent JIRA session. See New-JiraSession for more details.  If neither are supplied, this function will run with anonymous access to JIRA.
    #>
    [CmdletBinding()]
    param(
        # Project ID or key
        [Parameter(Mandatory = $true,
                   Position = 0)]
        [String] $Project,

        # Issue type ID or name
        [Parameter(Mandatory = $true,
                   Position = 1)]
        [String] $IssueType,

        [String] $ConfigFile,

        # Credentials to use to connect to Jira
        [Parameter(Mandatory = $false)]
        [System.Management.Automation.PSCredential] $Credential
    )

    begin
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Reading server from config file"
        try
        {
            $server = Get-JiraConfigServer -ConfigFile $ConfigFile -ErrorAction Stop
        } catch {
            $err = $_
            Write-Debug "[Get-JiraIssueCreateMetadata] Encountered an error reading the Jira server."
            throw $err
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Building URI for REST call based on parameters"
        $uri = "$server/rest/api/latest/issue/createmeta?"

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining project ID for project [$Project]"
        $projectObj = Get-JiraProject -Project $Project -Credential $Credential
        if ($projectObj)
        {
            $projectId = $projectObj.Id
            $uri = "${uri}projectIds=$projectId&"
        } else {
            throw "No project was found for the given Project [$Project]. Use Get-JiraProject for more information on this issue."
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining issue type ID for issue type [$IssueType]"
        $issueTypeObj = Get-JiraIssueType -IssueType $IssueType -Credential $Credential
        if ($issueTypeObj)
        {
            $issueTypeId = $issueTypeObj.Id
            $uri = "${uri}issuetypeIds=$issueTypeId&"
        } else {
            throw "No issue types were found for the given IssueType [$IssueType]. Use Get-JiraIssueType for more information on this issue."
        }

        $uri = "${uri}expand=projects.issuetypes.fields"
    }

    process
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Preparing for blastoff!"
        $jiraResult = Invoke-JiraMethod -Method Get -URI $uri -Credential $Credential

        if ($jiraResult)
        {
            if (@($jiraResult.projects).Count -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No project results were found. Throwing exception."
                throw "No projects were found for the given project [$Project]. Use Get-JiraProject for more details."
            } elseif (@($jiraResult.projects).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple project results were found. Throwing exception."
                throw "Multiple projects were found for the given project [$Project]. Refine the parameters to return only one project."
            }

            $projectId = $jiraResult.projects.id
            $projectKey = $jiraResult.projects.key

            Write-Debug "[Get-JiraIssueCreateMetadata] Identified project key: [$Project]"

            if (@($jiraResult.projects.issuetypes) -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No issue type results were found. Throwing exception."
                throw "No issue types were found for the given issue type [$IssueType]. Use Get-JiraIssueType for more details."
            } elseif (@($jiraResult.projects.issuetypes).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple issue type results were found. Throwing exception."
                throw "Multiple issue types were found for the given issue type [$IssueType]. Refine the parameters to return only one issue type."
            }

            Write-Debug "[Get-JiraIssueCreateMetadata] Converting results to custom object"
            $global:DEBUG_metadata = $jiraResult
            $obj = ConvertTo-JiraCreateMetaField -InputObject $jiraResult

            Write-Debug "Outputting results"
            Write-Output $obj

#            Write-Output $jiraResult
        } else {
            Write-Debug "[Get-JiraIssueCreateMetadata] No results were returned from JIRA."
        }
    }
}

[net.servicepointmanager]::securityprotocol = [net.securityprotocoltype]::Tls12

$Credentials = New-Object System.Management.Automation.PSCredential((Get-Credential))

Get-JiraIssueCreateMetadata -Project "DOC" -IssueType Task -Credential $Credentials

$DEBUG_metadata|ConvertTo-Json -Depth 99`

**Comment by JoeJe1993** [comment] 2017-06-05 09:42
``Import-Module PSJira

Set-JiraConfigServer -Server 'https://[DOMAIN]:443/jira'

function Get-JiraIssueCreateMetadata
{
    <#
    .Synopsis
       Returns metadata required to create an issue in JIRA
    .DESCRIPTION
       This function returns metadata required to create an issue in JIRA - the fields that can be defined in the process of creating an issue.  This can be used to identify custom fields in order to pass them to New-JiraIssue.

       This function is particularly useful when your JIRA instance includes custom fields that are marked as mandatory.  The required fields can be identified from this See the examples for more details on this approach.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'TEST' -IssueType 'Bug'
       This example returns the fields available when creating an issue of type Bug under project TEST.
    .EXAMPLE
       Get-JiraIssueCreateMetadata -Project 'JIRA' -IssueType 'Bug' | ? {$_.Required -eq $true}
       This example returns fields available when creating an issue of type Bug under the project Jira.  It then uses Where-Object (aliased by the question mark) to filter only the fields that are required.
    .INPUTS
       This function does not accept pipeline input.
    .OUTPUTS
       This function outputs the PSJira.Field objects that represent JIRA's create metadata.
    .NOTES
       This function requires either the -Credential parameter to be passed or a persistent JIRA session. See New-JiraSession for more details.  If neither are supplied, this function will run with anonymous access to JIRA.
    #>
    [CmdletBinding()]
    param(
        # Project ID or key
        [Parameter(Mandatory = $true,
                   Position = 0)]
        [String] $Project,

        # Issue type ID or name
        [Parameter(Mandatory = $true,
                   Position = 1)]
        [String] $IssueType,

        [String] $ConfigFile,

        # Credentials to use to connect to Jira
        [Parameter(Mandatory = $false)]
        [System.Management.Automation.PSCredential] $Credential
    )

    begin
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Reading server from config file"
        try
        {
            $server = Get-JiraConfigServer -ConfigFile $ConfigFile -ErrorAction Stop
        } catch {
            $err = $_
            Write-Debug "[Get-JiraIssueCreateMetadata] Encountered an error reading the Jira server."
            throw $err
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Building URI for REST call based on parameters"
        $uri = "$server/rest/api/latest/issue/createmeta?"

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining project ID for project [$Project]"
        $projectObj = Get-JiraProject -Project $Project -Credential $Credential
        if ($projectObj)
        {
            $projectId = $projectObj.Id
            $uri = "${uri}projectIds=$projectId&"
        } else {
            throw "No project was found for the given Project [$Project]. Use Get-JiraProject for more information on this issue."
        }

        Write-Debug "[Get-JiraIssueCreateMetadata] Obtaining issue type ID for issue type [$IssueType]"
        $issueTypeObj = Get-JiraIssueType -IssueType $IssueType -Credential $Credential
        if ($issueTypeObj)
        {
            $issueTypeId = $issueTypeObj.Id
            $uri = "${uri}issuetypeIds=$issueTypeId&"
        } else {
            throw "No issue types were found for the given IssueType [$IssueType]. Use Get-JiraIssueType for more information on this issue."
        }

        $uri = "${uri}expand=projects.issuetypes.fields"
    }

    process
    {
        Write-Debug "[Get-JiraIssueCreateMetadata] Preparing for blastoff!"
        $jiraResult = Invoke-JiraMethod -Method Get -URI $uri -Credential $Credential

        if ($jiraResult)
        {
            if (@($jiraResult.projects).Count -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No project results were found. Throwing exception."
                throw "No projects were found for the given project [$Project]. Use Get-JiraProject for more details."
            } elseif (@($jiraResult.projects).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple project results were found. Throwing exception."
                throw "Multiple projects were found for the given project [$Project]. Refine the parameters to return only one project."
            }

            $projectId = $jiraResult.projects.id
            $projectKey = $jiraResult.projects.key

            Write-Debug "[Get-JiraIssueCreateMetadata] Identified project key: [$Project]"

            if (@($jiraResult.projects.issuetypes) -eq 0)
            {
                Write-Debug "[Get-JiraIssueCreateMetadata] No issue type results were found. Throwing exception."
                throw "No issue types were found for the given issue type [$IssueType]. Use Get-JiraIssueType for more details."
            } elseif (@($jiraResult.projects.issuetypes).Count -gt 1) {
                Write-Debug "[Get-JiraIssueCreateMetadata] Multiple issue type results were found. Throwing exception."
                throw "Multiple issue types were found for the given issue type [$IssueType]. Refine the parameters to return only one issue type."
            }

            Write-Debug "[Get-JiraIssueCreateMetadata] Converting results to custom object"
            $global:DEBUG_metadata = $jiraResult
            $obj = ConvertTo-JiraCreateMetaField -InputObject $jiraResult

            Write-Debug "Outputting results"
            Write-Output $obj

#            Write-Output $jiraResult
        } else {
            Write-Debug "[Get-JiraIssueCreateMetadata] No results were returned from JIRA."
        }
    }
}

[net.servicepointmanager]::securityprotocol = [net.securityprotocoltype]::Tls12

$Credentials = New-Object System.Management.Automation.PSCredential((Get-Credential))

Get-JiraIssueCreateMetadata -Project "DOC" -IssueType Task -Credential $Credentials

$DEBUG_metadata|ConvertTo-Json -Depth 99``

**Comment by lipkau** [comment] 2017-06-05 09:47
what is the content of `$DEBUG_metadata.projects`?

**Comment by lipkau** [comment] 2017-06-05 09:49
Can you send me `c:\temp\dump.xml` after running 
```posh
Export-Clixml -InputObject $DEBUG_metadata -Path c:\temp\dump.xml
```
?

**Comment by JoeJe1993** [comment] 2017-06-05 09:51
![image](https://cloud.githubusercontent.com/assets/29064065/26779344/e5e18684-49dc-11e7-9bfb-8f6d5297a5a6.png)

**Comment by JoeJe1993** [comment] 2017-06-05 09:58
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCustomObject</T>
      <T>System.Object</T>
    </TN>
    <MS>
      <S N="expand">projects</S>
      <Obj N="projects" RefId="1">
        <TNRef RefId="0" />
        <MS>
          <S N="expand">issuetypes</S>
          <S N="self">https://doccentral.co.uk/jira/rest/api/2/project/10100</S>
          <S N="id">10100</S>
          <S N="key">DOC</S>
          <S N="name">Doccentrics</S>
          <Obj N="avatarUrls" RefId="2">
            <TNRef RefId="0" />
            <MS>
              <S N="48x48">https://doccentral.co.uk/jira/secure/projectavatar?pid=10100&amp;avatarId=10201</S>
              <S N="24x24">https://doccentral.co.uk/jira/secure/projectavatar?size=small&amp;pid=10100&amp;avatarId=10201</S>
              <S N="16x16">https://doccentral.co.uk/jira/secure/projectavatar?size=xsmall&amp;pid=10100&amp;avatarId=10201</S>
              <S N="32x32">https://doccentral.co.uk/jira/secure/projectavatar?size=medium&amp;pid=10100&amp;avatarId=10201</S>
            </MS>
          </Obj>
          <Nil N="issuetypes" />
        </MS>
      </Obj>
    </MS>
  </Obj>
</Objs>

**Comment by JoeJe1993** [comment] 2017-06-05 09:59
GitHub doesn't accept xml documents, so just change the extension once downloaded.

[dump.txt](https://github.com/PSJira/PSJira/files/1051710/dump.txt)

**Comment by JoeJe1993** [comment] 2017-06-05 10:00
GitHub doesn't accept XML, so change the file extension to xml once downloaded.

[dump.txt](https://github.com/PSJira/PSJira/files/1051713/dump.txt)

**Comment by lipkau** [comment] 2017-06-05 10:08
I wasn't expecting that...
It seems to be a limitation of JIRA.

I will investigate further, but it doesn't look too promising

**Comment by JoeJe1993** [comment] 2017-06-06 08:43
Hi @lipkau, Any updates?

**Comment by JoeJe1993** [comment] 2017-06-07 10:41
Bump.

**Comment by replicaJunction** [comment] 2017-06-08 16:36
In your provided screenshot, [issuetypes is null](https://cloud.githubusercontent.com/assets/29064065/26778801/b0e42c7c-49da-11e7-8007-d0c63a2aa695.png), which is what's causing the error - see [lines 36 and 37 of ConvertTo-JiraCreateMetaField](https://github.com/PSJira/PSJira/blob/master/PSJira/Internal/ConvertTo-JiraCreateMetaField.ps1#L36-L37). We need to understand why this particular project (DOC, name was redacted in that screenshot) in your Jira instance isn't returning any issue types, as I've never seen that happen before.

I'm having trouble accessing the Atlassian documentation at the moment, but if you're an admin in your JIRA environment, go to JIRA Administration > Projects, select your DOC project, and hit the "Issue Types" link in the sidebar. If you're not an admin, please ask for this info from your administrator.

You can also get some info using `Get-JiraIssueType`. See if that list contains all of the items in the project view above.

* In the Web admin view, do you have any issue types defined? (If they don't contain proprietary info, please list them here.)
* What is your output from `Get-JiraIssueType`?
* Do you know of any other major differences in this project than in other projects in your environment?

**Comment by JoeJe1993** [comment] 2017-06-09 09:00
Issue types:
![image](https://user-images.githubusercontent.com/29064065/26968583-72817a70-4cfa-11e7-9166-707ce01c0b4b.png)

I'll grab the output of `Get-Jira_issue_type` in the next 5 - 10 mins

**Comment by JoeJe1993** [comment] 2017-06-09 09:12
Here's the output:

![image](https://user-images.githubusercontent.com/29064065/26969027-27fe819e-4cfc-11e7-99f1-e4d892d52e8f.png)

**Comment by JoeJe1993** [comment] 2017-06-09 09:26
FYI, here's the version of Jira Service Desk we're running

![image](https://user-images.githubusercontent.com/29064065/26969561-1a10e3a4-4cfe-11e7-9538-6d2f860dc6c9.png)

**Comment by lipkau** [comment] 2017-06-09 12:14
please run this code and give us the output json (**please redact the server name in the json**)

```posh
$myServer = "https://"
$myProject = "DOC"

$cred = (Get-Credential)
[String] $Username = $Cred.UserName
$token = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${Username}:$($Cred.GetNetworkCredential().Password)"))

$headers = @{    'Authorization' = "Basic $token" }

(Invoke-WebRequest -Uri "$myServer/rest/api/2/project/$myProject" -Headers $headers -Method "GET" -UseBasicParsing).Content
```

**Comment by JoeJe1993** [comment] 2017-06-09 13:02
![image](https://user-images.githubusercontent.com/29064065/26976578-4c0a4198-4d1c-11e7-93c6-56ca7347a1b5.png)

**Comment by lipkau** [comment] 2017-06-09 13:04
```posh
$myServer = "https://"
$myProject = "DOC"

$cred = (Get-Credential)
[String] $Username = $Cred.UserName
$token = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${Username}:$($Cred.GetNetworkCredential().Password)"))

$headers = @{    'Authorization' = "Basic $token" }

Invoke-WebRequest -Uri "$myServer/rest/api/2/project/$myProject" -Headers $headers -Method "GET" -UseBasicParsing | convertto-json
```

**Comment by JoeJe1993** [comment] 2017-06-09 13:06
![image](https://user-images.githubusercontent.com/29064065/26976694-d8497ffc-4d1c-11e7-9d8f-84c13911b267.png)

**Comment by JoeJe1993** [comment] 2017-06-09 13:08
![image](https://user-images.githubusercontent.com/29064065/26976755-22026690-4d1d-11e7-8c7f-30908dadde6a.png)

**Comment by lipkau** [comment] 2017-06-09 13:10
```posh
$myServer = "https://"
$myProject = "DOC"

$cred = (Get-Credential)
[String] $Username = $Cred.UserName
$token = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${Username}:$($Cred.GetNetworkCredential().Password)"))

$headers = @{    'Authorization' = "Basic $token" }

try {
$webResponse = Invoke-WebRequest -Uri "$myServer/rest/api/2/project/$myProject" -Headers $headers -Method "GET" -UseBasicParsing
} catch {
$webResponse = $_.Exception.Response
}
$webResponse | convertto-json
```

**Comment by JoeJe1993** [comment] 2017-06-09 13:13
No error this time, literally nothing returned.

![image](https://user-images.githubusercontent.com/29064065/26976886-c12f244c-4d1d-11e7-8d78-8d9f085645e9.png)

**Comment by lipkau** [comment] 2017-06-09 13:18
`$webresponse` is empty??

**Comment by lipkau** [comment] 2017-06-09 13:18
```posh
$myServer = "https://"

$cred = (Get-Credential)
[String] $Username = $Cred.UserName
$token = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${Username}:$($Cred.GetNetworkCredential().Password)"))

$headers = @{    'Authorization' = "Basic $token" }

try {
$webResponse = Invoke-WebRequest -Uri "$myServer/rest/api/2/project" -Headers $headers -Method "GET" -UseBasicParsing
} catch {
$webResponse = $_.Exception.Response
}
$webResponse | convertto-json
```

**Comment by JoeJe1993** [comment] 2017-06-09 13:39
![image](https://user-images.githubusercontent.com/29064065/26977932-7e6035f8-4d21-11e7-837b-85b38c36e730.png)

**Comment by JoeJe1993** [comment] 2017-06-09 13:46
![image](https://user-images.githubusercontent.com/29064065/26978182-7049465c-4d22-11e7-8e78-49a3d03c3040.png)

**Comment by JoeJe1993** [comment] 2017-06-09 13:50
I have discovered that this may be an internal issue, I'll get back to you with further results shortly.

**Comment by JoeJe1993** [comment] 2017-06-09 14:18
UPDATE: So to get the API to work in my browser, I had to login manually via that same browser session.

It seems that the username and password in `Get-Credential` is not getting passed onto the API in your test script.

**Comment by JoeJe1993** [comment] 2017-06-09 14:22
![image](https://user-images.githubusercontent.com/29064065/26979624-631dc6a6-4d27-11e7-8210-133e20961e83.png)

**Comment by JoeJe1993** [comment] 2017-06-09 14:26
![image](https://user-images.githubusercontent.com/29064065/26979793-f706a356-4d27-11e7-9330-8a30015bd47a.png)

**Comment by JoeJe1993** [comment] 2017-06-09 14:31
Seems that some objects have different properties

![image](https://user-images.githubusercontent.com/29064065/26980004-b751cfb4-4d28-11e7-9fcc-428668e93c4c.png)

**Comment by lipkau** [comment] 2017-06-09 23:05
Is it only on New-JiraIssue that that happens?
Does Get-JiraIssue or Set-JiraIssue work on that project?

**Comment by lipkau** [comment] 2017-06-12 13:52
It appears that running the command get-jiraissuecreatmetadata is being run differently when called be the user and by new-jiraissue.
I will investigate once I am at a pc

**Comment by JoeJe1993** [comment] 2017-06-12 14:52
`Get-JiraIssue` works perfectly fine.

**Comment by JoeJe1993** [comment] 2017-06-12 14:58
I can also confirm that `Set-JiraIssue` works. However, I had to specify the -Credential parameter twice in order to get it to work.

`Get-JiraIssue -Key DOC-600 -Credential $Creds|Set-JiraIssue -Description "Test123" -Credential $Creds`

**Comment by JoeJe1993** [comment] 2017-06-13 15:57
Hi @lipkau, any updates?

**Comment by lipkau** [comment] 2017-06-13 20:01
What version of the module are you using?
`Get-Module PSJira -ListAvailable`

**Comment by lipkau** [comment] 2017-06-13 20:33
can you show me how this url looks in your browser?
@JoeJe1993 : `https://-----------------/rest/api/latest/issue/createmeta?projectIds=10100&issuetypeIds=10002&expand=projects.issuetypes.fields`
@JohnTheDon01 : `https://-----------------/rest/api/latest/issue/createmeta?projectIds=11200&issuetypeIds=10301&expand=projects.issuetypes.fields`

**Comment by JoeJe1993** [comment] 2017-06-14 08:33
![image](https://user-images.githubusercontent.com/29064065/27123029-7d7754d4-50e4-11e7-9e49-70767727ff4a.png)

**Comment by JoeJe1993** [comment] 2017-06-14 08:36
![image](https://user-images.githubusercontent.com/29064065/27123166-ee1469de-50e4-11e7-8979-3c0d5b10e355.png)

**Comment by JoeJe1993** [comment] 2017-06-14 08:42
I can't find the API you're referencing to in the API browser, the closest I came to was this:

![image](https://user-images.githubusercontent.com/29064065/27123436-c7974f32-50e5-11e7-8758-b62631c66178.png)

**Comment by lipkau** [comment] 2017-06-14 11:57
that's the same thing.
`/rest/api/latest` will use `/rest/api/2`, as long as 2 is the latest.

@JoeJe1993  I need the full result of that url

**Comment by JoeJe1993** [comment] 2017-06-14 12:09
@lipkau That is the full result. Here it is in plain-text:

`{"expand":"projects","projects":[{"expand":"issuetypes","self":"https://[DOMAIN]/jira/rest/api/2/project/10100","id":"10100","key":"DOC","name":"[NAME]","avatarUrls":{"48x48":"https://[DOMAIN]/jira/secure/projectavatar?pid=10100&avatarId=10201","24x24":"https://[DOMAIN]/jira/secure/projectavatar?size=small&pid=10100&avatarId=10201","16x16":"https://[DOMAIN]/jira/secure/projectavatar?size=xsmall&pid=10100&avatarId=10201","32x32":"https://[DOMAIN]/jira/secure/projectavatar?size=medium&pid=10100&avatarId=10201"},"issuetypes":[]}]}`

**Comment by JoeJe1993** [comment] 2017-06-15 08:14
Hi @lipkau, any updates?

**Comment by lipkau** [comment] 2017-06-15 18:21
Either _Service Desk_ works differently... or this is a jira bug.

According to your screenshot, you have 5 issue types used by the Project.
However, the API designed to give you the metadata of what fields are **required**, which are **optional**, what are the **AllowedValues** , etc is saying the project has no issuetypes.

I think I can get a trial version of _Service Desk_ for my test server.
If I do, I will install it and try it out.
I might have time tomorrow or Sunday.

If you want to speed things up, you could use this information and ask in the atlassian community site if anyone knows anything about this.
Or you could report a bug.

If anyone else has a server with _Service Desk_, I would appreciate some help with this, as I have 0 experience with this product

**Comment by brianbunke** [comment] 2017-08-12 14:53
I just created my first JIRA Service Desk ticket via the API yesterday.

I was not able to get JiraPS `2.1.0.90` to create a ticket in a Service Desk project. I consider myself pretty up-to-speed on the code base, and I spent about 15 minutes debugging. Here's the bad news: Nothing was obviously wrong.

Instead of spending hours making sure, I explored JIRA Service Desk's REST API endpoints instead, and successfully created a test ticket before the weekend.

JIRA SD REST API reference:
Cloud: [developer.atlassian.com](https://developer.atlassian.com/cloud/jira/service-desk/rest/)
Server: [docs.atlassian.com](https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/)

The most important thing I learned: JIRA ID #s are not the same as JIRA SD ID #s. Here are some rough examples from memory:

|Name|Type|JIRA ID|JIRA SD ID|
|---|---|---|---|
|TEST|Project|10110|2|
|Get IT Help|Request Type|10222|25|

This raises messy questions.

- Is anyone going to spend hours trying to make SD accept a normal JIRA API request?
  - My answer is definitely _no_
- So, should JiraPS be extended to detect and accommodate for this?
- Or should JIRA SD be deemed "unsupported," with recommendations to start a standalone repo?

**Comment by lipkau** [comment] 2017-09-26 06:56
I have create 3 different kinds of Service Desk projects in my jira:
![image](https://user-images.githubusercontent.com/4992870/30846390-c2d4663e-a297-11e7-91a0-ff80a53a3929.png)

All 3 have these Issue Types:
![image](https://user-images.githubusercontent.com/4992870/30846425-e91fc20c-a297-11e7-9353-c8d448132237.png)

With this setup I was able to:
* get all the metadata of that project (incl. the issuetypes):  
![image](https://user-images.githubusercontent.com/4992870/30846486-2e0cbab4-a298-11e7-9b86-466107664f69.png)
* create a new issue:  
![image](https://user-images.githubusercontent.com/4992870/30846555-6d445f34-a298-11e7-900b-8411d62fd940.png)

I did find an issue for the CLI of jira with the same behavior. It appear to be a matter of permissions:
https://bobswift.atlassian.net/browse/JCLI-768?focusedCommentId=32437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-32437
As I am no expert on Service Desk, I don't know how to help with that.

**Comment by brianbunke** [comment] 2017-09-26 15:25
Ok, you made me curious, and I'd like to try replicating on my end.

Cloud or server? What versions of JIRA & SD?

**Comment by lipkau** [comment] 2017-09-27 06:39
Cloud
> ```
> PS Projects:\jiraps> Get-JiraServerInfo
> baseUrl        : https://powershell.atlassian.net
> version        : 1000.1323.0
> versionNumbers : {1000, 1323, 0}
> deploymentType : Cloud
> buildNumber    : 100062
> buildDate      : 2017-09-26T00:00:00.000+0200
> serverTime     : 2017-09-27T08:39:04.861+0200
> scmInfo        : f3c60100df073e3576f9741fb7a3dc759b416fde
> serverTitle    : JIRA
> ```

**Comment by brianbunke** [comment] 2017-11-03 22:55
Just got back to testing this, conveniently with `v2.4`:

I can confirm that the most basic form of `New-JiraIssue` works against vanilla Service Desk projects in both JIRA Server (`7.5.1`) and Cloud. My problem previously was with an overcomplicated SD project that had some involved field requirements.

**Comment by lipkau** [comment] 2017-11-04 00:41
@JoeJe1993 and @JognTheDon01
Please test again with latest module version.
If it doesn't work, let me know the jira version you are running.
Ideally you would also test this with a fresh SD project.

I will close this issue in 2 weeks if I don't get feedback

**Closed** 2017-11-13 07:18 UTC
Labels: Issue:Question, Resolution:Answered
