### ISSUE TITLE
Null username error when submitting New-JiraIssue

### ISSUE THREAD

**Issue by quadrilo44** [AtlassianPS/JiraPS#403] opened 2020-02-17 04:04 UTC
## Description

From today, when creating a new issue, I am getting the following errors:

```powershell
Get-JiraUser : Cannot bind argument to parameter 'UserName' because it is null.
At \\USERPATH\Documents\WindowsPowerShell\Modules\JiraPS\2.12.5\JiraPS.psm1:2773 char:40
+                 Get-JiraUser -UserName $result.Name -Exact
+                                        ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-JiraUser], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-JiraUser

Invoke-JiraMethod :
reporter
--------
Reporter is required.
At \\USERPATH\Documents\WindowsPowerShell\Modules\JiraPS\2.12.5\JiraPS.psm1:3842 char:27
+             if ($result = Invoke-JiraMethod @parameter) {
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Invoke-JiraMethod], RuntimeException
    + FullyQualifiedErrorId : InvalidResponse.Status400,Invoke-JiraMethod
```

## Steps To Reproduce

Add new issue using the New-JiraIssue command.

## Expected behavior

Issue should be created successfully

## Your Environment

```powershell
Get-Module JiraPS -ListAvailable | Select Name, Version
Name   Version
----   -------
JiraPS 2.12.5

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.1146
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.1146
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Possible Solution

Looks like the "Name" attribute used in "Get-JiraUser -UserName $result.Name -Exact" is no longer returned.

**Comment by LaurentGoderre** [comment] 2020-02-21 22:20
This seems to be caused by the fact that the `Name` column in the `Get-JiraUser` function is empty

**Comment by jeffadavidson** [comment] 2020-02-21 22:40
I agree with @LaurentGoderre. The `New-JiraIssue` is attempting to get a reporter using `Get-JiraUser` and returning null instead. 

A possible work around is to provide a reporter directly in the parameters you provide.  EG
```powershell
New-JiraIssue -Project "SomeProject" -IssueType "Bug" -Summary "Test Reporter Issue" -Reporter "Anonymous"

OR 

$Parameters = @{
  Project = "SomeProject"
  IssueType = "Bug"
  Summary = "Test Reporter Issue"
  Reporter = "Anonymous"
}

New-JiraIssue @Parameters
```

**Comment by jeffadavidson** [comment] 2020-02-21 23:33
So I was looking into this a bit more. It looks like the root cause might be JIRA [removing username(s)](https://developer.atlassian.com/cloud/jira/platform/api-changes-for-user-privacy-announcement/) from their endpoints due to GDPR. Account IDs have replaced them it seems

**Comment by quadrilo44** [comment] 2020-02-22 01:01
They remove `name` for privacy reasons but keep `emailAddress` and `displayName`? Weird.

I suspect this is also the cause of the other couple of recent issues to do with Reporter and Assignee failing.

**Comment by lipkau** [comment] 2020-02-24 00:15
Thank you for reporting this.
This behavior has the same cause as #404 .
I am closing this as a duplicate. please follow that ticket for keeping up-to-date

**Closed by lipkau** 2020-02-24 00:15 UTC

**Comment by LaurentGoderre** [comment] 2020-02-24 16:51
#407
