### ISSUE TITLE
WARNING: Jira returned HTTP error 500 - InternalServerError

### ISSUE THREAD

**Issue by RealWorldPowerShell** [AtlassianPS/JiraPS#260] opened 2018-05-16 12:42 UTC
Created a new Jira issue and added it to a variable, then i tried to add a attachment to the newly created Jira issue where i get a "WARNING: Jira returned HTTP error 500 - InternalServerError"

### Expected Behavior
File to be added to the new jira issue.

### Current Behavior
"WARNING: Jira returned HTTP error 500 - InternalServerError"

### Steps to Reproduce (for bugs)

1. $newissue = New-JiraIssue -Project $Project -IssueType $IssueType -Summary $Summary -Description $Description
2. Add-JiraIssueAttachment -Issue $newissue -FilePath "C:\temp\out.txt"
3.
4.

### Your Environment

> ```powershell
> Get-Module JiraPS -ListAvailable | select version
> $PSVersionTable
> ```
Get-Module JiraPS -ListAvailable | select version
Version
-------
2.7.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lipkau** [comment] 2018-05-16 13:29
This is a duplicate of #248 
Please add your comment there.

**Closed by lipkau** 2018-05-16 13:29 UTC
Labels: Area:Module, Issue:Bug, Resolution:Duplicate
